# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Metalknights
email: metalknightsFTC@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Go forward, the future never waits
baseurl: "/" # the subpath of your site, e.g. /blog note that it must _also_ be defined in classic-jekyll-theme.scss!
url: "https://metalknights.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: knights12651
facebook_username: MetalKnightsRobotics
youtube_channelid: UCqOI3QK_AAuPuIFYd2v5XCg # the part in the URL bar after youtube.com/channel/
youtube_displayname: Metal Knights FTC 12651
github_username:  metalknightsFTC
instagram_username: metal_knights12651

# Build settings
markdown: kramdown
keep_files: [assets, icons]
exclude: [README.md]
remote_theme: balancingrock/classic-jekyll-theme
plugins:
  - jekyll-feed
